version: "3.7"

services:
  node_1:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./microservices/micr1:/app
      - ./proto:/proto
    command: nest start
    working_dir: /app

  node_2:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./microservices/micr2:/app
      - ./proto:/proto
    command: nest start
    working_dir: /app

  node_prisma2:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./microservices/micr_prisma:/app
      - ./proto:/proto
    command: nest start
    depends_on: 
      - mysql
    working_dir: /app

  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql  
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    # ports: 
    #   - 3307:3306
    
  node_client:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - ./proto:/proto
    command: nest start
    working_dir: /app
    ports: 
      - 3000:3000
    depends_on: 
      - node_1
      - node_2