version: "3.7"

services:
  node:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./microservices/micr1:/app
      - ./proto:/proto
    command: sh run.sh
    working_dir: /app
    